### ISSUE TITLE
Unsupported file types, e.g. dwg

### ISSUE THREAD

**Issue by heyse-dc** [xperseguers/t3ext-file_list#13]
Is there a configuration option to configure unknown file types like *.dwg?
When uploading DWG files we get this message:
Causal\FileList\Controller\FileController ERROR:
The configuration of the file_list plugin is incorrect: Unsupported file ***.dwg (image/vnd.dwg)

**Comment by xperseguers** [comment]
Don't know how to reproduce. I downloaded a dwg file from http://www.cadsample.com/autocad/rc-servo-motor-autocad-3d-dwg-drawing/ and put it into a folder listed with the plugin:

![Documents__Lions_Club_Broye-Vully_](https://user-images.githubusercontent.com/646805/74837062-f30d1080-5320-11ea-8fc8-1bf8f9a3e6af.png)

**Comment by xperseguers** [comment]
Well, I checked where the exception could be raised and this has nothing to do with EXT:file, the exception is raised from `\TYPO3\CMS\Core\Imaging\ImageMagickFile::resolvePrefix()`. PHP doc of that method reads:

```
    /**
     * Resolves according ImageMagic/GraphicsMagic format (e.g. 'png:', 'jpg:', ...).
     * + in case mime-type could be resolved and is configured, it takes precedence
     * + otherwise resolved mime-type extension of mime.magick database is used if available
     *   (includes custom settings with $GLOBALS['TYPO3_CONF_VARS']['SYS']['FileInfo']['fileExtensionToMimeType'])
     * + otherwise "safe" and allowed file extension is used (jpg, png, gif, webp, tif, ...)
     * + potentially malicious script formats (eps, ps, ...) are not allowed
     *
     * @return string
     * @throws Exception
     */
```

Thus it looks like you have misconfigured `$GLOBALS['TYPO3_CONF_VARS`]['GFX']['imagefile_ext']` by adding the `dwg` file extension. This is wrong since graphicsmagick and imagemagick cannot handle such file extension and trying to generate a thumbnail fails for those files.

**Comment by heyse-dc** [comment]
Thx for your support, its a while ago, but I think your right. We configured it with
$GLOBALS['TYPO3_CONF_VARS]['SYS']['textfile_ext'] as a Textfile
