### ISSUE TITLE
Umlauts as first letter disappear

### ISSUE THREAD

**Issue by optodelp** [xperseguers/t3ext-file_list#20]
We have some files in a folder like 'Übersicht_über_Whatever.pdf'. In the plugin, the starting Umlaut is cut away. The second one is fine.

When clicking it fails to open, because of the missing first letter.

As workaround, we are using files like 'Uebersicht....', but that's ugly.

**Comment by xperseguers** [comment]
Don't know how to reproduce, this just works fine for me.

**Comment by optodelp** [comment]
Yes, it's odd. Charset issues should affect both umlauts. It's a Centos machine. The path is mapped via cifs from a samba server. Logging in with ssh, it shows the umlauts correct. The locale is set to de_DE.utf8.

**Comment by xperseguers** [comment]
Are you sure you are using the templates that come with the extension? Default, no special view, nothing? I could think of a problem if somehow there's a grouping on the first character for instance, because if done with `substr` instead of a `mb_` method, this would leave the 2-bytes UTF8 character cut in half...

**Comment by xperseguers** [comment]
lack of further info
