### ISSUE TITLE
Exception: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by tomladud** [xperseguers/t3ext-file_list#28]
Hi,
when I try to list files within a folder/subfolder and  "Allow browsing to subfolders" is checked, I got the following error:

Causal\FileList\Controller\FileController ERROR:
The configuration of the file_list plugin is incorrect: Serialization of 'Closure' is not allowed

TYPO3: 10.4.6
PHP: 7.2.33

Is this a bug? Thanks in advance

**Comment by AureliusHogan** [comment]
Same problem here.

**Comment by xperseguers** [comment]
This is supposed to be fixed. Please check: #23

**Comment by sebdavid** [comment]
Same problem by my side.

Last tag/release of the extension is 2.4.2. The mentionned fix has been done after that. No version has been released since that.

I manually change the Helper.php file with the fix supplied in #23, and it works.

Do you know when a new release of the extension will be out?

**Comment by xperseguers** [comment]
on it.
