### ISSUE TITLE
Navigation to subfolders not possible

### ISSUE THREAD

**Issue by matze120** [xperseguers/t3ext-file_list#31]
If you use the file_list plugin in a the news system then it's not possible to browse throu the folders.   
The folder path is restricted to a folder with serveral subfolders and files. The files are displayed correctly.  
Instead of the content in the subfolder you get the message from the news system that the article is not avialable. 

I'm using:  
version 2.5.0 of the plugin  
Typo3 10.4.4  
version 8.30 of the news system

**Comment by xperseguers** [comment]
You should try to debug and document the URL to your news detail, and the URL that is used to browse to a subfolder. I suspect that the link to the subfolder simply misses the `tx_news[news]` parameter. That's something you should logically be able to adapt on your own by overriding the templates and asking the links to be generated with existing additional parameters in the URL, so that you get both the `tx_news[news]` parameter AND the file_list-related parameters for browsing to the subfolder.

Thanks for trying and reporting afterwards.

**Comment by xperseguers** [comment]
@matze120 reading again about what you wrote, is it possible that somehow you put a file_list plugin within a news article and this problem occurs while showing the detail of that news? That would explain the "article is not available" error since when navigating to a subfolder you will most probably miss the news parameter to "stay in the same news". If so I'd suggest to adapt the template on your side so that the news parameter is provided while creating the navigation link to the subfolder.
