### ISSUE TITLE
Compatibility with v11

### ISSUE THREAD

**Issue by karelkuijpers** [xperseguers/t3ext-file_list#38]
When will a version for Typo3 v11 be available?

**Comment by xperseguers** [comment]
Did you test the master branch?

**Comment by mediaessenz** [comment]
It's not working, because of changes in some core methods (File::getProperties and/or File::updateProperties) I gess.

File::getProperties called in EXT:file_list/Classes/Controller/FileController line 176 returns all properties *with* metadata. Unfortunately File::updateProperties only accepts files *without* metadata properties.

Maybe this is a core bug or a security enhancement.

So, is seems using updateProperties is not working anymore to add the "isNew" flag. Since this value is not persisted anywhere, the same "is new" check can also be done inside the fluid template I think.
The only thing which is needed there, is the timestamp until files should marked as new.

The part in the controller could look like this:
```php
/** @var Context $context */
$context = GeneralUtility::makeInstance(Context::class);
$currentTimestamp = $context->getPropertyFromAspect('date', 'timestamp');
$newTimestamp = $currentTimestamp - 86400 * (int)$this->settings['newDuration'];
$this->view->assign('newTimestamp', $newTimestamp);
```

The part in the fluid tempate:
```html
<f:if condition="{settings.newDuration} && {file.properties.creation_date} >= {newTimestamp}">
    <span class="badge badge-secondary"><f:translate key="newFile" /></span>
</f:if>
```

**Comment by xperseguers** [comment]
@mediaessenz Do you want to create a PR? Then I guess the extension is working and I could then release soonish an official (major bumped) with info about this breaking change in the release info.

**Comment by mediaessenz** [comment]
I will create a PR.

Since you want to release a new major version, how about e.g. names of typoscript files (.typoscript instead of .txt)?

Just found another issue in the backend. When I open a file_list plugin, I get this deprecation warning, which comes from PHP8 I think:
Deprecated: Required parameter $pObj follows optional parameter $conf in /app/private/typo3conf/ext/file_list/Classes/Tca/TemplateLayoutSelector.php on line 35

I could create one PR for all issues I found. Or do you prefer one PR for each?

**Comment by xperseguers** [comment]
You can create a single PR but with multiple commits please

**Comment by stigfaerch** [comment]
@xperseguers When will you release a new 11LTS compatible version to TER / Packagist (new version, not just master).
