### ISSUE TITLE
Multiple file collection issue

### ISSUE THREAD

**Issue by ulriklpedersen** [xperseguers/t3ext-file_list#41]
When adding 2 or more file collections the plugin only loads N number of files to the list. N beeing the amount of files in the file collection with the most files.

The loaded files differs according to the sorting algorithm.

**Comment by xperseguers** [comment]
Thanks for reporting. This ticket lacks a comprehensive step by step explanation on how to reproduce. Please give a concrete example as it’s too vague and “generic” to actually get what it’s all about by reading it.

**Comment by ulriklpedersen** [comment]
> Thanks for reporting. This ticket lacks a comprehensive step by step explanation on how to reproduce. Please give a concrete example as it’s too vague and “generic” to actually get what it’s all about by reading it.

I will try.

1. Install file_list 2.5.0 on TYPO3 10.4.x
2. Insert file_list plugin on page, add ext template
3. Create file collection from folder containing 2 files
4. Create file collection from folder containing 4 files
5. On the page with plugin add both file collections to the content element
6. Observe that only 4 files will be shown in frontend - 6 files is expected

**Comment by xperseguers** [comment]
> 6. Observe that only 4 files will be shown in frontend - 6 files is expected

OK, will see. If you explained that those 4 files are the ones from the second folder, it could give a hint at once what the problem is supposed to be: only taking last configured group in the list, which could then be tested by adding the two groups in reverse order and check that then only 2 files are shown. You see?

Here I still have to test myself to see whether it’s that or those 4 files are a mix of any 4 files out of the 6 which are expected.

Not a big deal but hope you get how to report even better another time ;-)

**Comment by xperseguers** [comment]
I can't reproduce this on TYPO3 v11, with master branch.

By reading the change log, I see that it's been fixed already with #35.

So please use development version or wait for some official release (don't have a date to tell you right now).
